### ISSUE TITLE
Configurer karma et openSauceLabs

### ISSUE THREAD

**Issue by gtoubiana** [gtoubiana/acte#2]
- [x] Installer karma
- [x] Configurer les navigateurs (chrome, firefox, safari, opera, phantomjs) pour karma
- [x] Créer une tâche Gulp pour karma
- [x] Bug console en sortie du script gulp ! voir https://gist.github.com/renegare/9173656. `karma start --single-run`fonctionne correctement mais pas `karma start` !
- [x] Connecter Karma avec openSauceLabs
- [x] Créer une tâche gulp pour openSauceLabs
- [x] Liste des navigateurs de twbs Bootstrap
- [x] BUG pour un Exit propre en fin de script (revoir fichier de conf en racine => karma init) => fonctionne bien sur 1 seul test. Bugs avec beaucoup de navigateurs...
- [x] Badge avec test validé (bug failing actuel)
- [x] Configurer Travis ci - voir http://karma-runner.github.io/0.13/plus/travis.html
- [x] Mettre le fichier sauce.json dans le .gitignore

**Comment by gtoubiana** [comment]
- https://github.com/pythonandchips/glasgowjs-karma-saucelabs-gulp

**Comment by gtoubiana** [comment]
```
[![Sauce Test Status](https://saucelabs.com/browser-matrix/gtoubiana.svg)](https://saucelabs.com/u/gtoubiana)
```

**Comment by gtoubiana** [comment]
Voir https://github.com/karma-runner/karma-sauce-launcher/issues/14 pour un exit propre (problème avec Chrome ?)

**Comment by gtoubiana** [comment]
### Sauce Labs et Travis CI:

- https://docs.travis-ci.com/user/environment-variables/
- https://github.com/karma-runner/karma-sauce-launcher
- https://docs-staging.saucelabs.com/ci-integrations/travis-ci/
- http://samsaccone.com/posts/testing-with-travis-and-sauce-labs.html

```
sudo: required
dist: trusty
language: node_js
env:
  global:
    - SAUCE_USERNAME="gtoubiana"
    - secure: "pJkBwnuae9dKU5tEcCqccfS1QQw7/meEcfz63fM7ba7QJNjoA6BaXj08L5Z3Vb5vBmVPwBawxo5Hp0jC0r/Z/O0hGnAmz/Cz09L+cy7dSAZ9x4hvZePSja/UAusaB5ogMoO8l2b773MzgQeSmrLbExr9BWLeqEfjC2hFgdgHLaQ="
```
