### ISSUE TITLE
Valider le travis.yml

### ISSUE THREAD

**Issue by gtoubiana** [gtoubiana/acte#275]
Valider avec http://lint.travis-ci.org/

**Comment by gtoubiana** [comment]
in matrix.include.env section: does not support multiple values, dropping COVERALLS='1'
in matrix.include section: unexpected key addons, dropping

**Comment by gtoubiana** [comment]
voir
https://docs.travis-ci.com/user/sauce-connect/
https://blog.travis-ci.com/2013-05-03-introducing-addons/
https://github.com/travis-ci/travis-ci/issues/1788
https://github.com/travis-ci/travis-yaml/issues/100

**Comment by gtoubiana** [comment]
et
https://docs.travis-ci.com/user/environment-variables/

**Comment by gtoubiana** [comment]
Ce sont de faux positifs. Je vais documenter le code

```
matrix:
  include:
    - node_js: 'stable'
      env:
        - SAUCELABS='1' COVERALLS='1'
      # Faux positif dans http://lint.travis-ci.org/
      addons:
        sauce_connect: true
```
